### ISSUE TITLE
Wrong recipes, causing decyncs

### ISSUE THREAD

**Issue by deniszholob** [Klonan/factory-floor#3]
A couple of inconsistencies found
![](https://cdn.discordapp.com/attachments/461264919434756107/461349128106934272/unknown.png)

![](https://cdn.discordapp.com/attachments/461264919434756107/461332019981451274/unknown.png)

Some know wrong recipes:
* Oil product barrels
* Nuke bomb
* purple, gray science
* Uranium Cannon Shell

**Comment by Klonan** [comment]
There is no way the scenario can change the recipes, it must be some other mod, or your save game has become corrupted
