### ISSUE TITLE
Lots of random desyncs

### ISSUE THREAD

**Issue by jahands** [Klonan/factory-floor#5]
A few things that cause desyncs:
- Spawning centrifuges
- Oil stuff
- Spawning radars through requester chests

Most desyncs seem to happen to players other than the first one that joined (myself when I created the save in SP before moving it to a server).

## World used
[Factory-Floor.zip](https://github.com/Klonan/factory-floor/files/2139728/Factory-Floor.zip)

## Server logs
[factorio-current.log](https://github.com/Klonan/factory-floor/files/2139734/factorio-current.log)
[factorio-previous.log](https://github.com/Klonan/factory-floor/files/2139735/factorio-previous.log)

## Desync reports
I created these by logging in as player 0 (the first player to join this scenario) and a new player. The new player is always the one to desync, not player 0.

- Desync when new player joins: [desync-report-2018-06-26_23-02-17.zip](https://github.com/Klonan/factory-floor/files/2139726/desync-report-2018-06-26_23-02-17.zip)
  - In this desync, player 0 is connected. A new player tries to join. New player desyncs, player 0 does not.

- Desync when player 0 spawns/buys a Centrifuge, other players desync: 
[desync-report-2018-06-26_23-07-57.zip](https://github.com/Klonan/factory-floor/files/2139733/desync-report-2018-06-26_23-07-57.zip)

**Comment by jahands** [comment]
Sometimes it seems like we're doing nothing and it desyncs

**Comment by jahands** [comment]
Will get desync logs on here asap

**Comment by jahands** [comment]
Placing a centrifuge desyncs other players

**Comment by jahands** [comment]
I have a feeling something weird may be going on because I loaded the scenario via the mod portal, created the map locally in single player, and then uploaded it to the server....maybe?

**Comment by jahands** [comment]
Running `/c game.player.force.reset_recipes()` seems to have fixed some stuff related to spawning (buying) things

**Comment by Klonan** [comment]
I think your map has become corrupted somehow, I cannot reproduce any of the issues, and nobody else has reported any desyncs at all
