### ISSUE TITLE
Max floors?

### ISSUE THREAD

**Issue by jahands** [Klonan/factory-floor#6]
I remember reading somewhere that there can only be 256 floors. But I'm running this as a public server so often players will join (creating a floor) and then leave. So it'd be nice for the floor count to be unlimited (or something really high.) There's ever more than a handful of people on anyway.

What's the current floor limit?

**Comment by Klonan** [comment]
Each player is on their own force, and the force limit is 256, or something, so it is an engine limitation that cannot be worked around
